# Learn more about configuring your app:
# https://shopify.dev/docs/apps/tools/cli/configuration

name = "ThemeDiff"
client_id = "4b629de297f9e67fa0c6c0567dbe209c"
application_url = "https://your-tunnel.trycloudflare.com"
embedded = true

[access_scopes]
scopes = "read_themes,read_products"

[auth]
redirect_urls = [
  "https://your-tunnel.trycloudflare.com/auth/callback",
  "https://your-tunnel.trycloudflare.com/auth/shopify/callback",
  "https://your-tunnel.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
